### PR TITLE
[WIP] add header link of whitepaper in en and ja

### PR DESCRIPTION
**Pull request by fiestared**
@sot528 
sorry that I can't complete this task.

### CODE REVIEW

**Comment by sot528** [comment]
@fiestared 
Here you are. ;)

**Comment by fiestared** [comment]
@sot528 Thanks a lot!

**Comment by fiestared** [comment]
@sot528 wow, could you leave review to merge it?

**Comment by fiestared** [comment]
@sot528 I modified marigin on PC browser. I'll also modify smartphone margin later though it seems not bad.

**Pull request merged**
