### PR TITLE
files about privacy policy are removed

### PR DESCRIPTION
**Pull request by fiestared**
@sot528 please check the points below.
- deleted privacy policy link from footer
- deleted files which is related to privacy policy
- no style collapse( I worry if I deleted wrong file)

### CODE REVIEW

**Comment by sot528** [comment]
[nits]
Finally we removed all of markdown resources. 😂 
So please remove related package from `package.json` via the command:
- `yarn remove jstransformer-markdown-it`

And commit `package.json` and `yarn.lock`.

**Comment by sot528** [comment]
[nits]
Also, please remove `src/includes/navbar_without_links.pug`

**Comment by fiestared** [comment]
@sot528 Done! Check it out!

**Comment by sot528** [comment]
@fiestared 
LGTM!
[LGTM](http://lgtm.in/i/44Tm0Evaq)

**Pull request merged**
