### PR TITLE
added meet us on header menu

### PR DESCRIPTION
**Pull request by fiestared**
@sot528 added a header link to our social & mail links
- named the link "meet us"
check if the word is not odd, and coding is correct.

### CODE REVIEW

**Comment by fiestared** [comment]
@sot528 I also added fb link in footer. please check it.

**Comment by sot528** [comment]
Looks good.
One point. Please fix mobile layout.


The code is around here.
- https://github.com/AlisProject/welcome/blob/add-headerlink/src/scss/home.scss#L408

**Comment by sot528** [comment]
And this PR's title & description is not enough.
You also added FB icon to footer.
-  https://github.com/AlisProject/welcome/pull/82/commits/19560667b92ed1626f75224c0164ef00f3355639

Let me know like that point next time. ;)

**Comment by fiestared** [comment]
@sot528 I'm sorry that I only check on iphone6. From now I'll check on iphone5. And I alos apologize for not changing pull request title. I just left comment but will change title next time.

**Comment by fiestared** [comment]
@sot528 And I fixed so please check it!

**Comment by sot528** [comment]
@fiestared 
LGTM!

**Pull request merged**
